name: csv
on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Generate CSV
        run: make update_csv
      - name: Check difference
        run: git diff --exit-code devops/csv/collection.csv